

// File generated by OpenXava: Wed Dec 19 17:26:02 CET 2007
// Archivo generado por OpenXava: Wed Dec 19 17:26:02 CET 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Color		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IColor  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_name = "name"; 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	public static final String PROPERTY_number = "number"; 	
	Integer getNumber() throws RemoteException; 	
	public static final String PROPERTY_sample = "sample"; 	
	java.lang.String getSample() throws RemoteException; 	
	public static final String PROPERTY_version = "version"; 
	int getVersion() throws RemoteException;
	void setVersion(int version) throws RemoteException;		

	// References/Referencias

	// Methods 


}