

// File generated by OpenXava: Thu Jun 07 11:41:22 CEST 2007
// Archivo generado por OpenXava: Thu Jun 07 11:41:22 CEST 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Delivery		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IDelivery  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	java.lang.String getIncidents() throws RemoteException;
	void setIncidents(java.lang.String incidents) throws RemoteException; 
	String getDriverType() throws RemoteException;
	void setDriverType(String driverType) throws RemoteException; 
	int getDistance() throws RemoteException;
	void setDistance(int distance) throws RemoteException; 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException; 	
	java.util.Date getDateAsLabel() throws RemoteException; 
	String getVehicle() throws RemoteException;
	void setVehicle(String vehicle) throws RemoteException; 
	java.lang.String getRemarks() throws RemoteException;
	void setRemarks(java.lang.String remarks) throws RemoteException; 	
	int getNumber() throws RemoteException; 	
	String getTransportMode() throws RemoteException; 
	String getEmployee() throws RemoteException;
	void setEmployee(String employee) throws RemoteException; 
	java.util.Date getDate() throws RemoteException;
	void setDate(java.util.Date date) throws RemoteException;	

	java.util.Collection getDetails() throws RemoteException;		

	// References/Referencias 

	// Invoice : Reference/Referencia
	
	org.openxava.test.model.IInvoice getInvoice() throws RemoteException;
	void setInvoice(org.openxava.test.model.IInvoice newInvoice) throws RemoteException; 

	// Shipment : Reference/Referencia
	
	org.openxava.test.model.IShipment getShipment() throws RemoteException;
	void setShipment(org.openxava.test.model.IShipment newShipment) throws RemoteException; 

	// Carrier : Reference/Referencia
	
	org.openxava.test.model.ICarrier getCarrier() throws RemoteException;
	void setCarrier(org.openxava.test.model.ICarrier newCarrier) throws RemoteException; 

	// Type : Reference/Referencia
	
	org.openxava.test.model.IDeliveryType getType() throws RemoteException;
	void setType(org.openxava.test.model.IDeliveryType newType) throws RemoteException;

	// Methods 


}