

// File generated by OpenXava: Fri Dec 23 12:06:45 CET 2005
// Archivo generado por OpenXava: Fri Dec 23 12:06:45 CET 2005

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: SellerLevel		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ISellerLevel  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException; 	
	String getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}