

// File generated by OpenXava: Wed Jul 12 11:13:26 CEST 2006
// Archivo generado por OpenXava: Wed Jul 12 11:13:26 CEST 2006

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Size		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ISize  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	int getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}