

// File generated by OpenXava: Mon Jul 09 13:16:55 CEST 2007
// Archivo generado por OpenXava: Mon Jul 09 13:16:55 CEST 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Year		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IYear  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	int getYear() throws RemoteException;
	void setYear(int year) throws RemoteException;		

	// References/Referencias

	// Methods 


}