

// File generated by OpenXava: Tue Apr 12 18:28:51 CEST 2005
// Archivo generado por OpenXava: Tue Apr 12 18:28:51 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR

package org.openxava.test.ejb;

public class Detail implements java.io.Serializable {

	// Attributes/Atributos 
	private int type; 
	private int subfamily;



	// Properties/Propiedades 
	public int getType() {
		return type;
	}
	public void setType(int newType) {
		this.type = newType;
	} 
	public int getSubfamily() {
		return subfamily;
	}
	public void setSubfamily(int newSubfamily) {
		this.subfamily = newSubfamily;
	}

	// References
	

}