

// File generated by OpenXava: Fri Jun 24 09:55:39 CEST 2005
// Archivo generado por OpenXava: Fri Jun 24 09:55:39 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Clerk		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.ejb;

import java.math.*;
import java.rmi.RemoteException;


public interface IClerk  {	

	// Properties/Propiedades 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	int getOfficeNumber() throws RemoteException; 	
	int getNumber() throws RemoteException; 	
	int getZoneNumber() throws RemoteException;		

	// References/Referencias

	// Methods 


}