

// File generated by OpenXava: Mon Jun 13 10:59:21 CEST 2005
// Archivo generado por OpenXava: Mon Jun 13 10:59:21 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: SellerLevel		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.ejb;

import java.math.*;
import java.rmi.RemoteException;


public interface ISellerLevel  {	

	// Properties/Propiedades 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException; 	
	String getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}