

// File generated by OpenXava: Thu Jul 28 11:06:43 CEST 2005
// Archivo generado por OpenXava: Thu Jul 28 11:06:43 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Warehouse		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.ejb;

import java.math.*;
import java.rmi.RemoteException;


public interface IWarehouse  {	

	// Properties/Propiedades 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	int getNumber() throws RemoteException; 	
	int getZoneNumber() throws RemoteException;		

	// References/Referencias

	// Methods 


}