/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model.xejb;

/**
 * CMP layer for Invoice.
 */
public abstract class InvoiceCMP
   extends org.openxava.test.model.xejb.InvoiceBean
   implements javax.ejb.EntityBean
{

   public org.openxava.test.model.InvoiceData getData()
   {
      org.openxava.test.model.InvoiceData dataHolder = null;
      try
      {
         dataHolder = new org.openxava.test.model.InvoiceData();

         dataHolder.set_Comment( get_Comment() );
         dataHolder.set_Date( get_Date() );
         dataHolder.set_Paid( get_Paid() );
         dataHolder.setYear( getYear() );
         dataHolder.set_VatPercentage( get_VatPercentage() );
         dataHolder.setNumber( getNumber() );
         dataHolder.set_Customer_number( get_Customer_number() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void setData( org.openxava.test.model.InvoiceData dataHolder )
   {
      try
      {
         set_Comment( dataHolder.get_Comment() );
         set_Date( dataHolder.get_Date() );
         set_Paid( dataHolder.get_Paid() );
         set_VatPercentage( dataHolder.get_VatPercentage() );
         set_Customer_number( dataHolder.get_Customer_number() );

      }
      catch (Exception e)
      {
         throw new javax.ejb.EJBException(e);
      }
   }

   public void ejbLoad() 
   {
      super.ejbLoad();
   }

   public void ejbStore() 
   {
         super.ejbStore();
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      InvoiceValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() 
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private org.openxava.test.model.InvoiceValue InvoiceValue = null;

   public org.openxava.test.model.InvoiceValue getInvoiceValue()
   {
      InvoiceValue = new org.openxava.test.model.InvoiceValue();
      try
         {
            InvoiceValue.setComment( getComment() );
            InvoiceValue.setDate( getDate() );
            InvoiceValue.setPaid( isPaid() );
            InvoiceValue.setYearDiscount( getYearDiscount() );
            InvoiceValue.setDetailsCount( getDetailsCount() );
            InvoiceValue.setConsiderable( isConsiderable() );
            InvoiceValue.setSellerDiscount( getSellerDiscount() );
            InvoiceValue.setAmountsSum( getAmountsSum() );
            InvoiceValue.setImportance( getImportance() );
            InvoiceValue.setYear( getYear() );
            InvoiceValue.setCustomerDiscount( getCustomerDiscount() );
            InvoiceValue.setVatPercentage( getVatPercentage() );
            InvoiceValue.setCustomerTypeDiscount( getCustomerTypeDiscount() );
            InvoiceValue.setVat( getVat() );
            InvoiceValue.setNumber( getNumber() );
            InvoiceValue.setCustomer_number( getCustomer_number() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return InvoiceValue;
   }

   public void setInvoiceValue( org.openxava.test.model.InvoiceValue valueHolder )
   {

	  try
	  {
		 setComment( valueHolder.getComment() );
		 setDate( valueHolder.getDate() );
		 setPaid( valueHolder.isPaid() );
		 setYearDiscount( valueHolder.getYearDiscount() );
		 setDetailsCount( valueHolder.getDetailsCount() );
		 setConsiderable( valueHolder.isConsiderable() );
		 setSellerDiscount( valueHolder.getSellerDiscount() );
		 setAmountsSum( valueHolder.getAmountsSum() );
		 setImportance( valueHolder.getImportance() );
		 setCustomerDiscount( valueHolder.getCustomerDiscount() );
		 setVatPercentage( valueHolder.getVatPercentage() );
		 setCustomerTypeDiscount( valueHolder.getCustomerTypeDiscount() );
		 setVat( valueHolder.getVat() );
		 setCustomer_number( valueHolder.getCustomer_number() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.String get_Comment() ;

   public abstract void set_Comment( java.lang.String _Comment ) ;

   public abstract java.sql.Date get_Date() ;

   public abstract void set_Date( java.sql.Date _Date ) ;

   public abstract java.lang.String get_Paid() ;

   public abstract void set_Paid( java.lang.String _Paid ) ;

   public abstract int getYear() ;

   public abstract void setYear( int year ) ;

   public abstract java.math.BigDecimal get_VatPercentage() ;

   public abstract void set_VatPercentage( java.math.BigDecimal _VatPercentage ) ;

   public abstract int getNumber() ;

   public abstract void setNumber( int number ) ;

   public abstract int get_Customer_number() ;

   public abstract void set_Customer_number( int _Customer_number ) ;

}
