

// File generated by OpenXava: Mon Jun 18 10:15:24 CEST 2007
// Archivo generado por OpenXava: Mon Jun 18 10:15:24 CEST 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Course		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ICourse  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException; 	
	int getNumber() throws RemoteException; 	
	int getYear() throws RemoteException;		

	// References/Referencias

	// Methods 


}