

// File generated by OpenXava: Wed Oct 19 17:30:54 CEST 2005
// Archivo generado por OpenXava: Wed Oct 19 17:30:54 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Family2		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IFamily2  {	

	// Properties/Propiedades 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException; 	
	int getNumber() throws RemoteException;		

	// References/Referencias

	// Methods 


}