

// File generated by OpenXava: Wed Jan 18 11:38:33 CET 2006
// Archivo generado por OpenXava: Wed Jan 18 11:38:33 CET 2006

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: State		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IState  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	String getFullName() throws RemoteException; 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	String getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}