

// File generated by OpenXava: Fri May 25 12:16:05 CEST 2007
// Archivo generado por OpenXava: Fri May 25 12:16:05 CEST 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Warehouse		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IWarehouse  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	int getNumber() throws RemoteException; 	
	int getZoneNumber() throws RemoteException;		

	// References/Referencias

	// Methods 


}