

// File generated by OpenXava: Fri Sep 16 18:01:19 CEST 2005
// Archivo generado por OpenXava: Fri Sep 16 18:01:19 CEST 2005

// WARNING: NO EDIT
// OJO: NO EDITAR

package org.openxava.test.model;

public class SubfamilyInfo implements java.io.Serializable {

	// Attributes/Atributos 
	private org.openxava.test.model.IFamily2 family; 
	private org.openxava.test.model.ISubfamily2 subfamily;



	// Properties/Propiedades

	// References 
	public org.openxava.test.model.IFamily2 getFamily() {
		return family;
	}
	public void setFamily(org.openxava.test.model.IFamily2 newFamily) {
		this.family = newFamily;
	} 
	public org.openxava.test.model.ISubfamily2 getSubfamily() {
		return subfamily;
	}
	public void setSubfamily(org.openxava.test.model.ISubfamily2 newSubfamily) {
		this.subfamily = newSubfamily;
	}
	

}