/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model.xejb;

/**
 * CMP layer for Clerk.
 */
public abstract class ClerkCMP
   extends org.openxava.test.model.xejb.ClerkBean
   implements javax.ejb.EntityBean
{

   public org.openxava.test.model.ClerkData getData()
   {
      org.openxava.test.model.ClerkData dataHolder = null;
      try
      {
         dataHolder = new org.openxava.test.model.ClerkData();

         dataHolder.set_Name( get_Name() );
         dataHolder.setOfficeNumber( getOfficeNumber() );
         dataHolder.setNumber( getNumber() );
         dataHolder.setZoneNumber( getZoneNumber() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void setData( org.openxava.test.model.ClerkData dataHolder )
   {
      try
      {
         set_Name( dataHolder.get_Name() );

      }
      catch (Exception e)
      {
         throw new javax.ejb.EJBException(e);
      }
   }

   public void ejbLoad() 
   {
      super.ejbLoad();
   }

   public void ejbStore() 
   {
         super.ejbStore();
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      ClerkValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() 
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private org.openxava.test.model.ClerkValue ClerkValue = null;

   public org.openxava.test.model.ClerkValue getClerkValue()
   {
      ClerkValue = new org.openxava.test.model.ClerkValue();
      try
         {
            ClerkValue.setName( getName() );
            ClerkValue.setOfficeNumber( getOfficeNumber() );
            ClerkValue.setNumber( getNumber() );
            ClerkValue.setZoneNumber( getZoneNumber() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return ClerkValue;
   }

   public void setClerkValue( org.openxava.test.model.ClerkValue valueHolder )
   {

	  try
	  {
		 setName( valueHolder.getName() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.String get_Name() ;

   public abstract void set_Name( java.lang.String _Name ) ;

   public abstract int getOfficeNumber() ;

   public abstract void setOfficeNumber( int officeNumber ) ;

   public abstract int getNumber() ;

   public abstract void setNumber( int number ) ;

   public abstract int getZoneNumber() ;

   public abstract void setZoneNumber( int zoneNumber ) ;

}
