/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model.xejb;

/**
 * CMP layer for CustomerContactPerson.
 */
public abstract class CustomerContactPersonCMP
   extends org.openxava.test.model.xejb.CustomerContactPersonBean
   implements javax.ejb.EntityBean
{

   public org.openxava.test.model.CustomerContactPersonData getData()
   {
      org.openxava.test.model.CustomerContactPersonData dataHolder = null;
      try
      {
         dataHolder = new org.openxava.test.model.CustomerContactPersonData();

         dataHolder.set_Name( get_Name() );
         dataHolder.set_Customer_number( get_Customer_number() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void setData( org.openxava.test.model.CustomerContactPersonData dataHolder )
   {
      try
      {
         set_Name( dataHolder.get_Name() );

      }
      catch (Exception e)
      {
         throw new javax.ejb.EJBException(e);
      }
   }

   public void ejbLoad() 
   {
      super.ejbLoad();
   }

   public void ejbStore() 
   {
         super.ejbStore();
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      CustomerContactPersonValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() 
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private org.openxava.test.model.CustomerContactPersonValue CustomerContactPersonValue = null;

   public org.openxava.test.model.CustomerContactPersonValue getCustomerContactPersonValue()
   {
      CustomerContactPersonValue = new org.openxava.test.model.CustomerContactPersonValue();
      try
         {
            CustomerContactPersonValue.setName( getName() );
            CustomerContactPersonValue.setCustomer_number( getCustomer_number() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return CustomerContactPersonValue;
   }

   public void setCustomerContactPersonValue( org.openxava.test.model.CustomerContactPersonValue valueHolder )
   {

	  try
	  {
		 setName( valueHolder.getName() );
		 setCustomer_number( valueHolder.getCustomer_number() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.String get_Name() ;

   public abstract void set_Name( java.lang.String _Name ) ;

   public abstract int get_Customer_number() ;

   public abstract void set_Customer_number( int _Customer_number ) ;

}
