/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model.xejb;

/**
 * CMP layer for Driver.
 */
public abstract class DriverCMP
   extends org.openxava.test.model.xejb.DriverBean
   implements javax.ejb.EntityBean
{

   public org.openxava.test.model.DriverData getData()
   {
      org.openxava.test.model.DriverData dataHolder = null;
      try
      {
         dataHolder = new org.openxava.test.model.DriverData();

         dataHolder.set_Type( get_Type() );
         dataHolder.set_Name( get_Name() );
         dataHolder.set_Number( get_Number() );
         dataHolder.set_DrivingLicence_level( get_DrivingLicence_level() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void setData( org.openxava.test.model.DriverData dataHolder )
   {
      try
      {
         set_Type( dataHolder.get_Type() );
         set_Name( dataHolder.get_Name() );
         set_DrivingLicence_level( dataHolder.get_DrivingLicence_level() );

      }
      catch (Exception e)
      {
         throw new javax.ejb.EJBException(e);
      }
   }

   public void ejbLoad() 
   {
      super.ejbLoad();
   }

   public void ejbStore() 
   {
         super.ejbStore();
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      DriverValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() 
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private org.openxava.test.model.DriverValue DriverValue = null;

   public org.openxava.test.model.DriverValue getDriverValue()
   {
      DriverValue = new org.openxava.test.model.DriverValue();
      try
         {
            DriverValue.setType( getType() );
            DriverValue.setName( getName() );
            DriverValue.setNumber( getNumber() );
            DriverValue.setDrivingLicence_type( getDrivingLicence_type() );
            DriverValue.setDrivingLicence_level( getDrivingLicence_level() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return DriverValue;
   }

   public void setDriverValue( org.openxava.test.model.DriverValue valueHolder )
   {

	  try
	  {
		 setType( valueHolder.getType() );
		 setName( valueHolder.getName() );
		 setNumber( valueHolder.getNumber() );
		 setDrivingLicence_type( valueHolder.getDrivingLicence_type() );
		 setDrivingLicence_level( valueHolder.getDrivingLicence_level() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.String get_Type() ;

   public abstract void set_Type( java.lang.String _Type ) ;

   public abstract java.lang.String get_Name() ;

   public abstract void set_Name( java.lang.String _Name ) ;

   public abstract java.lang.Integer get_Number() ;

   public abstract void set_Number( java.lang.Integer _Number ) ;

   public abstract int get_DrivingLicence_level() ;

   public abstract void set_DrivingLicence_level( int _DrivingLicence_level ) ;

}
