/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Data object for Customer.
 */
public class CustomerData
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;
   private java.lang.String _Website;
   private java.lang.String _Email;
   private java.lang.String _Name;
   private java.lang.String _Remarks;
   private int number;
   private java.lang.Integer _Type;
   private java.lang.String _Telephone;
   private byte[] _Photo;
   private java.lang.String _RelationWithSeller;
   private java.lang.String _Address_zipCode;
   private java.lang.String _Address_street;
   private java.lang.String _Address_city;
   private java.lang.String _Address_state_id;
   private java.lang.Integer _AlternateSeller_number;
   private java.lang.Integer _Seller_number;

   public CustomerData()
   {
   }

   public CustomerData( CustomerData otherData )
   {
      set_Website(otherData.get_Website());
      set_Email(otherData.get_Email());
      set_Name(otherData.get_Name());
      set_Remarks(otherData.get_Remarks());
      setNumber(otherData.getNumber());
      set_Type(otherData.get_Type());
      set_Telephone(otherData.get_Telephone());
      set_Photo(otherData.get_Photo());
      set_RelationWithSeller(otherData.get_RelationWithSeller());
      set_Address_zipCode(otherData.get_Address_zipCode());
      set_Address_street(otherData.get_Address_street());
      set_Address_city(otherData.get_Address_city());
      set_Address_state_id(otherData.get_Address_state_id());
      set_AlternateSeller_number(otherData.get_AlternateSeller_number());
      set_Seller_number(otherData.get_Seller_number());

   }

   public org.openxava.test.model.CustomerKey getPrimaryKey() {
     org.openxava.test.model.CustomerKey pk = new org.openxava.test.model.CustomerKey(this.getNumber());
     return pk;
   }

   public java.lang.String get_Website()
   {
      return this._Website;
   }
   public void set_Website( java.lang.String _Website )
   {
      this._Website = _Website;
   }

   public java.lang.String get_Email()
   {
      return this._Email;
   }
   public void set_Email( java.lang.String _Email )
   {
      this._Email = _Email;
   }

   public java.lang.String get_Name()
   {
      return this._Name;
   }
   public void set_Name( java.lang.String _Name )
   {
      this._Name = _Name;
   }

   public java.lang.String get_Remarks()
   {
      return this._Remarks;
   }
   public void set_Remarks( java.lang.String _Remarks )
   {
      this._Remarks = _Remarks;
   }

   public int getNumber()
   {
      return this.number;
   }
   public void setNumber( int number )
   {
      this.number = number;
   }

   public java.lang.Integer get_Type()
   {
      return this._Type;
   }
   public void set_Type( java.lang.Integer _Type )
   {
      this._Type = _Type;
   }

   public java.lang.String get_Telephone()
   {
      return this._Telephone;
   }
   public void set_Telephone( java.lang.String _Telephone )
   {
      this._Telephone = _Telephone;
   }

   public byte[] get_Photo()
   {
      return this._Photo;
   }
   public void set_Photo( byte[] _Photo )
   {
      this._Photo = _Photo;
   }

   public java.lang.String get_RelationWithSeller()
   {
      return this._RelationWithSeller;
   }
   public void set_RelationWithSeller( java.lang.String _RelationWithSeller )
   {
      this._RelationWithSeller = _RelationWithSeller;
   }

   public java.lang.String get_Address_zipCode()
   {
      return this._Address_zipCode;
   }
   public void set_Address_zipCode( java.lang.String _Address_zipCode )
   {
      this._Address_zipCode = _Address_zipCode;
   }

   public java.lang.String get_Address_street()
   {
      return this._Address_street;
   }
   public void set_Address_street( java.lang.String _Address_street )
   {
      this._Address_street = _Address_street;
   }

   public java.lang.String get_Address_city()
   {
      return this._Address_city;
   }
   public void set_Address_city( java.lang.String _Address_city )
   {
      this._Address_city = _Address_city;
   }

   public java.lang.String get_Address_state_id()
   {
      return this._Address_state_id;
   }
   public void set_Address_state_id( java.lang.String _Address_state_id )
   {
      this._Address_state_id = _Address_state_id;
   }

   public java.lang.Integer get_AlternateSeller_number()
   {
      return this._AlternateSeller_number;
   }
   public void set_AlternateSeller_number( java.lang.Integer _AlternateSeller_number )
   {
      this._AlternateSeller_number = _AlternateSeller_number;
   }

   public java.lang.Integer get_Seller_number()
   {
      return this._Seller_number;
   }
   public void set_Seller_number( java.lang.Integer _Seller_number )
   {
      this._Seller_number = _Seller_number;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("_Website=" + get_Website() + " " + "_Email=" + get_Email() + " " + "_Name=" + get_Name() + " " + "_Remarks=" + get_Remarks() + " " + "number=" + getNumber() + " " + "_Type=" + get_Type() + " " + "_Telephone=" + get_Telephone() + " " + "_Photo=" + get_Photo() + " " + "_RelationWithSeller=" + get_RelationWithSeller() + " " + "_Address_zipCode=" + get_Address_zipCode() + " " + "_Address_street=" + get_Address_street() + " " + "_Address_city=" + get_Address_city() + " " + "_Address_state_id=" + get_Address_state_id() + " " + "_AlternateSeller_number=" + get_AlternateSeller_number() + " " + "_Seller_number=" + get_Seller_number());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof CustomerData )
      {
         CustomerData lTest = (CustomerData) pOther;
         boolean lEquals = true;

         if( this._Website == null )
         {
            lEquals = lEquals && ( lTest._Website == null );
         }
         else
         {
            lEquals = lEquals && this._Website.equals( lTest._Website );
         }
         if( this._Email == null )
         {
            lEquals = lEquals && ( lTest._Email == null );
         }
         else
         {
            lEquals = lEquals && this._Email.equals( lTest._Email );
         }
         if( this._Name == null )
         {
            lEquals = lEquals && ( lTest._Name == null );
         }
         else
         {
            lEquals = lEquals && this._Name.equals( lTest._Name );
         }
         if( this._Remarks == null )
         {
            lEquals = lEquals && ( lTest._Remarks == null );
         }
         else
         {
            lEquals = lEquals && this._Remarks.equals( lTest._Remarks );
         }
         lEquals = lEquals && this.number == lTest.number;
         if( this._Type == null )
         {
            lEquals = lEquals && ( lTest._Type == null );
         }
         else
         {
            lEquals = lEquals && this._Type.equals( lTest._Type );
         }
         if( this._Telephone == null )
         {
            lEquals = lEquals && ( lTest._Telephone == null );
         }
         else
         {
            lEquals = lEquals && this._Telephone.equals( lTest._Telephone );
         }
         lEquals = lEquals && this._Photo == lTest._Photo;
         if( this._RelationWithSeller == null )
         {
            lEquals = lEquals && ( lTest._RelationWithSeller == null );
         }
         else
         {
            lEquals = lEquals && this._RelationWithSeller.equals( lTest._RelationWithSeller );
         }
         if( this._Address_zipCode == null )
         {
            lEquals = lEquals && ( lTest._Address_zipCode == null );
         }
         else
         {
            lEquals = lEquals && this._Address_zipCode.equals( lTest._Address_zipCode );
         }
         if( this._Address_street == null )
         {
            lEquals = lEquals && ( lTest._Address_street == null );
         }
         else
         {
            lEquals = lEquals && this._Address_street.equals( lTest._Address_street );
         }
         if( this._Address_city == null )
         {
            lEquals = lEquals && ( lTest._Address_city == null );
         }
         else
         {
            lEquals = lEquals && this._Address_city.equals( lTest._Address_city );
         }
         if( this._Address_state_id == null )
         {
            lEquals = lEquals && ( lTest._Address_state_id == null );
         }
         else
         {
            lEquals = lEquals && this._Address_state_id.equals( lTest._Address_state_id );
         }
         if( this._AlternateSeller_number == null )
         {
            lEquals = lEquals && ( lTest._AlternateSeller_number == null );
         }
         else
         {
            lEquals = lEquals && this._AlternateSeller_number.equals( lTest._AlternateSeller_number );
         }
         if( this._Seller_number == null )
         {
            lEquals = lEquals && ( lTest._Seller_number == null );
         }
         else
         {
            lEquals = lEquals && this._Seller_number.equals( lTest._Seller_number );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this._Website != null) ? this._Website.hashCode() : 0);

      result = 37*result + ((this._Email != null) ? this._Email.hashCode() : 0);

      result = 37*result + ((this._Name != null) ? this._Name.hashCode() : 0);

      result = 37*result + ((this._Remarks != null) ? this._Remarks.hashCode() : 0);

      result = 37*result + (int) number;

      result = 37*result + ((this._Type != null) ? this._Type.hashCode() : 0);

      result = 37*result + ((this._Telephone != null) ? this._Telephone.hashCode() : 0);

      if (_Photo != null) {
        for (int i=0; i<_Photo.length; i++)
        {
          long l = _Photo[i];
          result = 37*result + (int)(l^(l>>>32));
        }
      }

      result = 37*result + ((this._RelationWithSeller != null) ? this._RelationWithSeller.hashCode() : 0);

      result = 37*result + ((this._Address_zipCode != null) ? this._Address_zipCode.hashCode() : 0);

      result = 37*result + ((this._Address_street != null) ? this._Address_street.hashCode() : 0);

      result = 37*result + ((this._Address_city != null) ? this._Address_city.hashCode() : 0);

      result = 37*result + ((this._Address_state_id != null) ? this._Address_state_id.hashCode() : 0);

      result = 37*result + ((this._AlternateSeller_number != null) ? this._AlternateSeller_number.hashCode() : 0);

      result = 37*result + ((this._Seller_number != null) ? this._Seller_number.hashCode() : 0);

      return result;
   }

}
