/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Data object for FormulaIngredient.
 */
public class FormulaIngredientData
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;
   private java.lang.String oid;
   private java.lang.String _Accentuate_oid;
   private java.lang.String _Ingredient_oid;
   private java.lang.String _Formula_oid;
   private java.lang.String _AnotherFormula_oid;

   public FormulaIngredientData()
   {
   }

   public FormulaIngredientData( FormulaIngredientData otherData )
   {
      setOid(otherData.getOid());
      set_Accentuate_oid(otherData.get_Accentuate_oid());
      set_Ingredient_oid(otherData.get_Ingredient_oid());
      set_Formula_oid(otherData.get_Formula_oid());
      set_AnotherFormula_oid(otherData.get_AnotherFormula_oid());

   }

   public org.openxava.test.model.FormulaIngredientKey getPrimaryKey() {
     org.openxava.test.model.FormulaIngredientKey pk = new org.openxava.test.model.FormulaIngredientKey(this.getOid());
     return pk;
   }

   public java.lang.String getOid()
   {
      return this.oid;
   }
   public void setOid( java.lang.String oid )
   {
      this.oid = oid;
   }

   public java.lang.String get_Accentuate_oid()
   {
      return this._Accentuate_oid;
   }
   public void set_Accentuate_oid( java.lang.String _Accentuate_oid )
   {
      this._Accentuate_oid = _Accentuate_oid;
   }

   public java.lang.String get_Ingredient_oid()
   {
      return this._Ingredient_oid;
   }
   public void set_Ingredient_oid( java.lang.String _Ingredient_oid )
   {
      this._Ingredient_oid = _Ingredient_oid;
   }

   public java.lang.String get_Formula_oid()
   {
      return this._Formula_oid;
   }
   public void set_Formula_oid( java.lang.String _Formula_oid )
   {
      this._Formula_oid = _Formula_oid;
   }

   public java.lang.String get_AnotherFormula_oid()
   {
      return this._AnotherFormula_oid;
   }
   public void set_AnotherFormula_oid( java.lang.String _AnotherFormula_oid )
   {
      this._AnotherFormula_oid = _AnotherFormula_oid;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("oid=" + getOid() + " " + "_Accentuate_oid=" + get_Accentuate_oid() + " " + "_Ingredient_oid=" + get_Ingredient_oid() + " " + "_Formula_oid=" + get_Formula_oid() + " " + "_AnotherFormula_oid=" + get_AnotherFormula_oid());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof FormulaIngredientData )
      {
         FormulaIngredientData lTest = (FormulaIngredientData) pOther;
         boolean lEquals = true;

         if( this.oid == null )
         {
            lEquals = lEquals && ( lTest.oid == null );
         }
         else
         {
            lEquals = lEquals && this.oid.equals( lTest.oid );
         }
         if( this._Accentuate_oid == null )
         {
            lEquals = lEquals && ( lTest._Accentuate_oid == null );
         }
         else
         {
            lEquals = lEquals && this._Accentuate_oid.equals( lTest._Accentuate_oid );
         }
         if( this._Ingredient_oid == null )
         {
            lEquals = lEquals && ( lTest._Ingredient_oid == null );
         }
         else
         {
            lEquals = lEquals && this._Ingredient_oid.equals( lTest._Ingredient_oid );
         }
         if( this._Formula_oid == null )
         {
            lEquals = lEquals && ( lTest._Formula_oid == null );
         }
         else
         {
            lEquals = lEquals && this._Formula_oid.equals( lTest._Formula_oid );
         }
         if( this._AnotherFormula_oid == null )
         {
            lEquals = lEquals && ( lTest._AnotherFormula_oid == null );
         }
         else
         {
            lEquals = lEquals && this._AnotherFormula_oid.equals( lTest._AnotherFormula_oid );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.oid != null) ? this.oid.hashCode() : 0);

      result = 37*result + ((this._Accentuate_oid != null) ? this._Accentuate_oid.hashCode() : 0);

      result = 37*result + ((this._Ingredient_oid != null) ? this._Ingredient_oid.hashCode() : 0);

      result = 37*result + ((this._Formula_oid != null) ? this._Formula_oid.hashCode() : 0);

      result = 37*result + ((this._AnotherFormula_oid != null) ? this._AnotherFormula_oid.hashCode() : 0);

      return result;
   }

}
