/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Data object for Invoice.
 */
public class InvoiceData
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;
   private java.lang.String _Comment;
   private java.sql.Date _Date;
   private java.lang.String _Paid;
   private int year;
   private java.math.BigDecimal _VatPercentage;
   private int number;
   private int _Customer_number;

   public InvoiceData()
   {
   }

   public InvoiceData( InvoiceData otherData )
   {
      set_Comment(otherData.get_Comment());
      set_Date(otherData.get_Date());
      set_Paid(otherData.get_Paid());
      setYear(otherData.getYear());
      set_VatPercentage(otherData.get_VatPercentage());
      setNumber(otherData.getNumber());
      set_Customer_number(otherData.get_Customer_number());

   }

   public org.openxava.test.model.InvoiceKey getPrimaryKey() {
     org.openxava.test.model.InvoiceKey pk = new org.openxava.test.model.InvoiceKey(this.getYear(),this.getNumber());
     return pk;
   }

   public java.lang.String get_Comment()
   {
      return this._Comment;
   }
   public void set_Comment( java.lang.String _Comment )
   {
      this._Comment = _Comment;
   }

   public java.sql.Date get_Date()
   {
      return this._Date;
   }
   public void set_Date( java.sql.Date _Date )
   {
      this._Date = _Date;
   }

   public java.lang.String get_Paid()
   {
      return this._Paid;
   }
   public void set_Paid( java.lang.String _Paid )
   {
      this._Paid = _Paid;
   }

   public int getYear()
   {
      return this.year;
   }
   public void setYear( int year )
   {
      this.year = year;
   }

   public java.math.BigDecimal get_VatPercentage()
   {
      return this._VatPercentage;
   }
   public void set_VatPercentage( java.math.BigDecimal _VatPercentage )
   {
      this._VatPercentage = _VatPercentage;
   }

   public int getNumber()
   {
      return this.number;
   }
   public void setNumber( int number )
   {
      this.number = number;
   }

   public int get_Customer_number()
   {
      return this._Customer_number;
   }
   public void set_Customer_number( int _Customer_number )
   {
      this._Customer_number = _Customer_number;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("_Comment=" + get_Comment() + " " + "_Date=" + get_Date() + " " + "_Paid=" + get_Paid() + " " + "year=" + getYear() + " " + "_VatPercentage=" + get_VatPercentage() + " " + "number=" + getNumber() + " " + "_Customer_number=" + get_Customer_number());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof InvoiceData )
      {
         InvoiceData lTest = (InvoiceData) pOther;
         boolean lEquals = true;

         if( this._Comment == null )
         {
            lEquals = lEquals && ( lTest._Comment == null );
         }
         else
         {
            lEquals = lEquals && this._Comment.equals( lTest._Comment );
         }
         if( this._Date == null )
         {
            lEquals = lEquals && ( lTest._Date == null );
         }
         else
         {
            lEquals = lEquals && this._Date.equals( lTest._Date );
         }
         if( this._Paid == null )
         {
            lEquals = lEquals && ( lTest._Paid == null );
         }
         else
         {
            lEquals = lEquals && this._Paid.equals( lTest._Paid );
         }
         lEquals = lEquals && this.year == lTest.year;
         if( this._VatPercentage == null )
         {
            lEquals = lEquals && ( lTest._VatPercentage == null );
         }
         else
         {
            lEquals = lEquals && this._VatPercentage.equals( lTest._VatPercentage );
         }
         lEquals = lEquals && this.number == lTest.number;
         lEquals = lEquals && this._Customer_number == lTest._Customer_number;

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this._Comment != null) ? this._Comment.hashCode() : 0);

      result = 37*result + ((this._Date != null) ? this._Date.hashCode() : 0);

      result = 37*result + ((this._Paid != null) ? this._Paid.hashCode() : 0);

      result = 37*result + (int) year;

      result = 37*result + ((this._VatPercentage != null) ? this._VatPercentage.hashCode() : 0);

      result = 37*result + (int) number;

      result = 37*result + (int) _Customer_number;

      return result;
   }

}
