/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Value object for Product3.
 *
 */
public class Product3Value
   extends java.lang.Object
   implements java.io.Serializable 
{

   private static final long serialVersionUID = 1L;

   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private long number;
   private boolean numberHasBeenSet = false;
   private java.lang.String comments;
   private boolean commentsHasBeenSet = false;
   private java.lang.String family_oid;
   private boolean family_oidHasBeenSet = false;
   private org.openxava.test.model.SubfamilyInfo subfamily1;
   private boolean subfamily1HasBeenSet = false;
   private int subfamily1_family_number;
   private boolean subfamily1_family_numberHasBeenSet = false;
   private int subfamily1_subfamily_number;
   private boolean subfamily1_subfamily_numberHasBeenSet = false;
   private org.openxava.test.model.SubfamilyInfo subfamily2;
   private boolean subfamily2HasBeenSet = false;
   private int subfamily2_family_number;
   private boolean subfamily2_family_numberHasBeenSet = false;
   private int subfamily2_subfamily_number;
   private boolean subfamily2_subfamily_numberHasBeenSet = false;

   public Product3Value()
   {
   }

   //TODO Cloneable is better than this !
   public Product3Value( Product3Value otherValue )
   {
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	  this.number = otherValue.number;
	  numberHasBeenSet = true;
	  this.comments = otherValue.comments;
	  commentsHasBeenSet = true;
	  this.family_oid = otherValue.family_oid;
	  family_oidHasBeenSet = true;
	  this.subfamily1 = otherValue.subfamily1;
	  subfamily1HasBeenSet = true;
	  this.subfamily1_family_number = otherValue.subfamily1_family_number;
	  subfamily1_family_numberHasBeenSet = true;
	  this.subfamily1_subfamily_number = otherValue.subfamily1_subfamily_number;
	  subfamily1_subfamily_numberHasBeenSet = true;
	  this.subfamily2 = otherValue.subfamily2;
	  subfamily2HasBeenSet = true;
	  this.subfamily2_family_number = otherValue.subfamily2_family_number;
	  subfamily2_family_numberHasBeenSet = true;
	  this.subfamily2_subfamily_number = otherValue.subfamily2_subfamily_number;
	  subfamily2_subfamily_numberHasBeenSet = true;
   }

   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;
   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }
   public long getNumber()
   {
	  return this.number;
   }

   public void setNumber( long number )
   {
	  this.number = number;
	  numberHasBeenSet = true;
   }

   public boolean numberHasBeenSet(){
	  return numberHasBeenSet;
   }
   public java.lang.String getComments()
   {
	  return this.comments;
   }

   public void setComments( java.lang.String comments )
   {
	  this.comments = comments;
	  commentsHasBeenSet = true;
   }

   public boolean commentsHasBeenSet(){
	  return commentsHasBeenSet;
   }
   public java.lang.String getFamily_oid()
   {
	  return this.family_oid;
   }

   public void setFamily_oid( java.lang.String family_oid )
   {
	  this.family_oid = family_oid;
	  family_oidHasBeenSet = true;
   }

   public boolean family_oidHasBeenSet(){
	  return family_oidHasBeenSet;
   }
   public org.openxava.test.model.SubfamilyInfo getSubfamily1()
   {
	  return this.subfamily1;
   }

   public void setSubfamily1( org.openxava.test.model.SubfamilyInfo subfamily1 )
   {
	  this.subfamily1 = subfamily1;
	  subfamily1HasBeenSet = true;
   }

   public boolean subfamily1HasBeenSet(){
	  return subfamily1HasBeenSet;
   }
   public int getSubfamily1_family_number()
   {
	  return this.subfamily1_family_number;
   }

   public void setSubfamily1_family_number( int subfamily1_family_number )
   {
	  this.subfamily1_family_number = subfamily1_family_number;
	  subfamily1_family_numberHasBeenSet = true;
   }

   public boolean subfamily1_family_numberHasBeenSet(){
	  return subfamily1_family_numberHasBeenSet;
   }
   public int getSubfamily1_subfamily_number()
   {
	  return this.subfamily1_subfamily_number;
   }

   public void setSubfamily1_subfamily_number( int subfamily1_subfamily_number )
   {
	  this.subfamily1_subfamily_number = subfamily1_subfamily_number;
	  subfamily1_subfamily_numberHasBeenSet = true;
   }

   public boolean subfamily1_subfamily_numberHasBeenSet(){
	  return subfamily1_subfamily_numberHasBeenSet;
   }
   public org.openxava.test.model.SubfamilyInfo getSubfamily2()
   {
	  return this.subfamily2;
   }

   public void setSubfamily2( org.openxava.test.model.SubfamilyInfo subfamily2 )
   {
	  this.subfamily2 = subfamily2;
	  subfamily2HasBeenSet = true;
   }

   public boolean subfamily2HasBeenSet(){
	  return subfamily2HasBeenSet;
   }
   public int getSubfamily2_family_number()
   {
	  return this.subfamily2_family_number;
   }

   public void setSubfamily2_family_number( int subfamily2_family_number )
   {
	  this.subfamily2_family_number = subfamily2_family_number;
	  subfamily2_family_numberHasBeenSet = true;
   }

   public boolean subfamily2_family_numberHasBeenSet(){
	  return subfamily2_family_numberHasBeenSet;
   }
   public int getSubfamily2_subfamily_number()
   {
	  return this.subfamily2_subfamily_number;
   }

   public void setSubfamily2_subfamily_number( int subfamily2_subfamily_number )
   {
	  this.subfamily2_subfamily_number = subfamily2_subfamily_number;
	  subfamily2_subfamily_numberHasBeenSet = true;
   }

   public boolean subfamily2_subfamily_numberHasBeenSet(){
	  return subfamily2_subfamily_numberHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("description=" + getDescription() + " " + "number=" + getNumber() + " " + "comments=" + getComments() + " " + "family_oid=" + getFamily_oid() + " " + "subfamily1=" + getSubfamily1() + " " + "subfamily1_family_number=" + getSubfamily1_family_number() + " " + "subfamily1_subfamily_number=" + getSubfamily1_subfamily_number() + " " + "subfamily2=" + getSubfamily2() + " " + "subfamily2_family_number=" + getSubfamily2_family_number() + " " + "subfamily2_subfamily_number=" + getSubfamily2_subfamily_number());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && numberHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof Product3Value)
	  {
		 Product3Value that = (Product3Value) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 lEquals = lEquals && this.number == that.number;

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof Product3Value)
	  {
		 Product3Value that = (Product3Value) other;
		 boolean lEquals = true;
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.comments == null )
		 {
			lEquals = lEquals && ( that.comments == null );
		 }
		 else
		 {
			lEquals = lEquals && this.comments.equals( that.comments );
		 }
		 if( this.family_oid == null )
		 {
			lEquals = lEquals && ( that.family_oid == null );
		 }
		 else
		 {
			lEquals = lEquals && this.family_oid.equals( that.family_oid );
		 }
		 if( this.subfamily1 == null )
		 {
			lEquals = lEquals && ( that.subfamily1 == null );
		 }
		 else
		 {
			lEquals = lEquals && this.subfamily1.equals( that.subfamily1 );
		 }
		 lEquals = lEquals && this.subfamily1_family_number == that.subfamily1_family_number;
		 lEquals = lEquals && this.subfamily1_subfamily_number == that.subfamily1_subfamily_number;
		 if( this.subfamily2 == null )
		 {
			lEquals = lEquals && ( that.subfamily2 == null );
		 }
		 else
		 {
			lEquals = lEquals && this.subfamily2.equals( that.subfamily2 );
		 }
		 lEquals = lEquals && this.subfamily2_family_number == that.subfamily2_family_number;
		 lEquals = lEquals && this.subfamily2_subfamily_number == that.subfamily2_subfamily_number;

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

      result = 37*result + (int)(number^(number>>>32));

      result = 37*result + ((this.comments != null) ? this.comments.hashCode() : 0);

      result = 37*result + ((this.family_oid != null) ? this.family_oid.hashCode() : 0);

      result = 37*result + ((this.subfamily1 != null) ? this.subfamily1.hashCode() : 0);

      result = 37*result + (int) subfamily1_family_number;

      result = 37*result + (int) subfamily1_subfamily_number;

      result = 37*result + ((this.subfamily2 != null) ? this.subfamily2.hashCode() : 0);

      result = 37*result + (int) subfamily2_family_number;

      result = 37*result + (int) subfamily2_subfamily_number;

	  return result;
   }

}
