/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Remote interface for Receptionist.
 */
public interface ReceptionistRemote
   extends org.openxava.ejbx.EJBReplicable, org.openxava.test.model.IReceptionist
{

   public int getOid(  )
      throws java.rmi.RemoteException;

   public java.lang.String getName(  )
      throws java.rmi.RemoteException;

   public void setName( java.lang.String newName )
      throws java.rmi.RemoteException;

   public org.openxava.test.model.IDeliveryPlace getDeliveryPlace(  )
      throws java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote getDeliveryPlaceRemote(  )
      throws java.rmi.RemoteException;

   public void setDeliveryPlace( org.openxava.test.model.IDeliveryPlace newDeliveryPlace )
      throws java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceKey getDeliveryPlaceKey(  )
      throws java.rmi.RemoteException;

   public void setDeliveryPlaceKey( org.openxava.test.model.DeliveryPlaceKey key )
      throws java.rmi.RemoteException;

   public java.lang.String getDeliveryPlace_oid(  )
      throws java.rmi.RemoteException;

   public org.openxava.test.model.ReceptionistData getData(  )
      throws java.rmi.RemoteException;

   public void setData( org.openxava.test.model.ReceptionistData data )
      throws java.rmi.RemoteException;

   public org.openxava.test.model.ReceptionistValue getReceptionistValue(  )
      throws java.rmi.RemoteException;

   public void setReceptionistValue( org.openxava.test.model.ReceptionistValue value )
      throws java.rmi.RemoteException;

}
