/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Value object for Report.
 *
 */
public class ReportValue
   extends java.lang.Object
   implements java.io.Serializable 
{

   private static final long serialVersionUID = 1L;

   private java.lang.String oid;
   private boolean oidHasBeenSet = false;
   private java.lang.String name;
   private boolean nameHasBeenSet = false;
   private java.lang.String ranges_oid;
   private boolean ranges_oidHasBeenSet = false;

   public ReportValue()
   {
   }

   //TODO Cloneable is better than this !
   public ReportValue( ReportValue otherValue )
   {
	  this.oid = otherValue.oid;
	  oidHasBeenSet = true;
	  this.name = otherValue.name;
	  nameHasBeenSet = true;
	  this.ranges_oid = otherValue.ranges_oid;
	  ranges_oidHasBeenSet = true;
   }

   public java.lang.String getOid()
   {
	  return this.oid;
   }

   public void setOid( java.lang.String oid )
   {
	  this.oid = oid;
	  oidHasBeenSet = true;
   }

   public boolean oidHasBeenSet(){
	  return oidHasBeenSet;
   }
   public java.lang.String getName()
   {
	  return this.name;
   }

   public void setName( java.lang.String name )
   {
	  this.name = name;
	  nameHasBeenSet = true;
   }

   public boolean nameHasBeenSet(){
	  return nameHasBeenSet;
   }
   public java.lang.String getRanges_oid()
   {
	  return this.ranges_oid;
   }

   public void setRanges_oid( java.lang.String ranges_oid )
   {
	  this.ranges_oid = ranges_oid;
	  ranges_oidHasBeenSet = true;
   }

   public boolean ranges_oidHasBeenSet(){
	  return ranges_oidHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("oid=" + getOid() + " " + "name=" + getName() + " " + "ranges_oid=" + getRanges_oid());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && oidHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof ReportValue)
	  {
		 ReportValue that = (ReportValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.oid == null )
		 {
			lEquals = lEquals && ( that.oid == null );
		 }
		 else
		 {
			lEquals = lEquals && this.oid.equals( that.oid );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof ReportValue)
	  {
		 ReportValue that = (ReportValue) other;
		 boolean lEquals = true;
		 if( this.name == null )
		 {
			lEquals = lEquals && ( that.name == null );
		 }
		 else
		 {
			lEquals = lEquals && this.name.equals( that.name );
		 }
		 if( this.ranges_oid == null )
		 {
			lEquals = lEquals && ( that.ranges_oid == null );
		 }
		 else
		 {
			lEquals = lEquals && this.ranges_oid.equals( that.ranges_oid );
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.oid != null) ? this.oid.hashCode() : 0);

      result = 37*result + ((this.name != null) ? this.name.hashCode() : 0);

      result = 37*result + ((this.ranges_oid != null) ? this.ranges_oid.hashCode() : 0);

	  return result;
   }

}
