/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Data object for Service.
 */
public class ServiceData
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;
   private java.lang.Integer _Family;
   private java.lang.String _Description;
   private int number;
   private java.lang.Integer _Detail_free;
   private java.lang.Integer _Detail_subfamily;
   private java.lang.Integer _Detail_type;

   public ServiceData()
   {
   }

   public ServiceData( ServiceData otherData )
   {
      set_Family(otherData.get_Family());
      set_Description(otherData.get_Description());
      setNumber(otherData.getNumber());
      set_Detail_free(otherData.get_Detail_free());
      set_Detail_subfamily(otherData.get_Detail_subfamily());
      set_Detail_type(otherData.get_Detail_type());

   }

   public org.openxava.test.model.ServiceKey getPrimaryKey() {
     org.openxava.test.model.ServiceKey pk = new org.openxava.test.model.ServiceKey(this.getNumber());
     return pk;
   }

   public java.lang.Integer get_Family()
   {
      return this._Family;
   }
   public void set_Family( java.lang.Integer _Family )
   {
      this._Family = _Family;
   }

   public java.lang.String get_Description()
   {
      return this._Description;
   }
   public void set_Description( java.lang.String _Description )
   {
      this._Description = _Description;
   }

   public int getNumber()
   {
      return this.number;
   }
   public void setNumber( int number )
   {
      this.number = number;
   }

   public java.lang.Integer get_Detail_free()
   {
      return this._Detail_free;
   }
   public void set_Detail_free( java.lang.Integer _Detail_free )
   {
      this._Detail_free = _Detail_free;
   }

   public java.lang.Integer get_Detail_subfamily()
   {
      return this._Detail_subfamily;
   }
   public void set_Detail_subfamily( java.lang.Integer _Detail_subfamily )
   {
      this._Detail_subfamily = _Detail_subfamily;
   }

   public java.lang.Integer get_Detail_type()
   {
      return this._Detail_type;
   }
   public void set_Detail_type( java.lang.Integer _Detail_type )
   {
      this._Detail_type = _Detail_type;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("_Family=" + get_Family() + " " + "_Description=" + get_Description() + " " + "number=" + getNumber() + " " + "_Detail_free=" + get_Detail_free() + " " + "_Detail_subfamily=" + get_Detail_subfamily() + " " + "_Detail_type=" + get_Detail_type());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof ServiceData )
      {
         ServiceData lTest = (ServiceData) pOther;
         boolean lEquals = true;

         if( this._Family == null )
         {
            lEquals = lEquals && ( lTest._Family == null );
         }
         else
         {
            lEquals = lEquals && this._Family.equals( lTest._Family );
         }
         if( this._Description == null )
         {
            lEquals = lEquals && ( lTest._Description == null );
         }
         else
         {
            lEquals = lEquals && this._Description.equals( lTest._Description );
         }
         lEquals = lEquals && this.number == lTest.number;
         if( this._Detail_free == null )
         {
            lEquals = lEquals && ( lTest._Detail_free == null );
         }
         else
         {
            lEquals = lEquals && this._Detail_free.equals( lTest._Detail_free );
         }
         if( this._Detail_subfamily == null )
         {
            lEquals = lEquals && ( lTest._Detail_subfamily == null );
         }
         else
         {
            lEquals = lEquals && this._Detail_subfamily.equals( lTest._Detail_subfamily );
         }
         if( this._Detail_type == null )
         {
            lEquals = lEquals && ( lTest._Detail_type == null );
         }
         else
         {
            lEquals = lEquals && this._Detail_type.equals( lTest._Detail_type );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this._Family != null) ? this._Family.hashCode() : 0);

      result = 37*result + ((this._Description != null) ? this._Description.hashCode() : 0);

      result = 37*result + (int) number;

      result = 37*result + ((this._Detail_free != null) ? this._Detail_free.hashCode() : 0);

      result = 37*result + ((this._Detail_subfamily != null) ? this._Detail_subfamily.hashCode() : 0);

      result = 37*result + ((this._Detail_type != null) ? this._Detail_type.hashCode() : 0);

      return result;
   }

}
