/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Home interface for Subfamily2.
 */
public interface Subfamily2Home
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Subfamily2";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.model/Subfamily2";

   public org.openxava.test.model.Subfamily2Remote create(java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.Subfamily2Remote create(org.openxava.test.model.Subfamily2Data data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.Subfamily2Remote create(org.openxava.test.model.Subfamily2Value value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public java.util.Collection findByFamily(int number)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.Subfamily2Remote findByPrimaryKey(org.openxava.test.model.Subfamily2Key pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
