/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Data object for Worker.
 */
public class WorkerData
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;
   private java.lang.Integer id;
   private java.lang.String _NickName;
   private java.lang.String _FullName;

   public WorkerData()
   {
   }

   public WorkerData( WorkerData otherData )
   {
      setId(otherData.getId());
      set_NickName(otherData.get_NickName());
      set_FullName(otherData.get_FullName());

   }

   public org.openxava.test.model.WorkerKey getPrimaryKey() {
     org.openxava.test.model.WorkerKey pk = new org.openxava.test.model.WorkerKey(this.getId());
     return pk;
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }
   public void setId( java.lang.Integer id )
   {
      this.id = id;
   }

   public java.lang.String get_NickName()
   {
      return this._NickName;
   }
   public void set_NickName( java.lang.String _NickName )
   {
      this._NickName = _NickName;
   }

   public java.lang.String get_FullName()
   {
      return this._FullName;
   }
   public void set_FullName( java.lang.String _FullName )
   {
      this._FullName = _FullName;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("id=" + getId() + " " + "_NickName=" + get_NickName() + " " + "_FullName=" + get_FullName());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof WorkerData )
      {
         WorkerData lTest = (WorkerData) pOther;
         boolean lEquals = true;

         if( this.id == null )
         {
            lEquals = lEquals && ( lTest.id == null );
         }
         else
         {
            lEquals = lEquals && this.id.equals( lTest.id );
         }
         if( this._NickName == null )
         {
            lEquals = lEquals && ( lTest._NickName == null );
         }
         else
         {
            lEquals = lEquals && this._NickName.equals( lTest._NickName );
         }
         if( this._FullName == null )
         {
            lEquals = lEquals && ( lTest._FullName == null );
         }
         else
         {
            lEquals = lEquals && this._FullName.equals( lTest._FullName );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this._NickName != null) ? this._NickName.hashCode() : 0);

      result = 37*result + ((this._FullName != null) ? this._FullName.hashCode() : 0);

      return result;
   }

}
