/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb.xejb;

/**
 * CMP layer for Product3.
 */
public abstract class Product3CMP
   extends org.openxava.test.ejb.xejb.Product3Bean
   implements javax.ejb.EntityBean
{

   public org.openxava.test.ejb.Product3Data getData()
   {
      org.openxava.test.ejb.Product3Data dataHolder = null;
      try
      {
         dataHolder = new org.openxava.test.ejb.Product3Data();

         dataHolder.set_Comments( get_Comments() );
         dataHolder.set_Description( get_Description() );
         dataHolder.setNumber( getNumber() );
         dataHolder.set_Subfamily1_family_oid( get_Subfamily1_family_oid() );
         dataHolder.set_Subfamily1_subfamily_oid( get_Subfamily1_subfamily_oid() );
         dataHolder.set_Family_oid( get_Family_oid() );
         dataHolder.set_Subfamily2_family_oid( get_Subfamily2_family_oid() );
         dataHolder.set_Subfamily2_subfamily_oid( get_Subfamily2_subfamily_oid() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void setData( org.openxava.test.ejb.Product3Data dataHolder )
   {
      try
      {
         set_Comments( dataHolder.get_Comments() );
         set_Description( dataHolder.get_Description() );
         set_Subfamily1_family_oid( dataHolder.get_Subfamily1_family_oid() );
         set_Subfamily1_subfamily_oid( dataHolder.get_Subfamily1_subfamily_oid() );
         set_Family_oid( dataHolder.get_Family_oid() );
         set_Subfamily2_family_oid( dataHolder.get_Subfamily2_family_oid() );
         set_Subfamily2_subfamily_oid( dataHolder.get_Subfamily2_subfamily_oid() );

      }
      catch (Exception e)
      {
         throw new javax.ejb.EJBException(e);
      }
   }

   public void ejbLoad() 
   {
      super.ejbLoad();
   }

   public void ejbStore() 
   {
         super.ejbStore();
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      Product3Value = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() 
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private org.openxava.test.ejb.Product3Value Product3Value = null;

   public org.openxava.test.ejb.Product3Value getProduct3Value()
   {
      Product3Value = new org.openxava.test.ejb.Product3Value();
      try
         {
            Product3Value.setComments( getComments() );
            Product3Value.setDescription( getDescription() );
            Product3Value.setNumber( getNumber() );
            Product3Value.setSubfamily1( getSubfamily1() );
            Product3Value.setSubfamily1_family_oid( getSubfamily1_family_oid() );
            Product3Value.setSubfamily1_subfamily_oid( getSubfamily1_subfamily_oid() );
            Product3Value.setFamily_oid( getFamily_oid() );
            Product3Value.setSubfamily2( getSubfamily2() );
            Product3Value.setSubfamily2_family_oid( getSubfamily2_family_oid() );
            Product3Value.setSubfamily2_subfamily_oid( getSubfamily2_subfamily_oid() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return Product3Value;
   }

   public void setProduct3Value( org.openxava.test.ejb.Product3Value valueHolder )
   {

	  try
	  {
		 setComments( valueHolder.getComments() );
		 setDescription( valueHolder.getDescription() );
		 setSubfamily1( valueHolder.getSubfamily1() );
		 setSubfamily1_family_oid( valueHolder.getSubfamily1_family_oid() );
		 setSubfamily1_subfamily_oid( valueHolder.getSubfamily1_subfamily_oid() );
		 setFamily_oid( valueHolder.getFamily_oid() );
		 setSubfamily2( valueHolder.getSubfamily2() );
		 setSubfamily2_family_oid( valueHolder.getSubfamily2_family_oid() );
		 setSubfamily2_subfamily_oid( valueHolder.getSubfamily2_subfamily_oid() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.String get_Comments() ;

   public abstract void set_Comments( java.lang.String _Comments ) ;

   public abstract java.lang.String get_Description() ;

   public abstract void set_Description( java.lang.String _Description ) ;

   public abstract long getNumber() ;

   public abstract void setNumber( long number ) ;

   public abstract java.lang.String get_Subfamily1_family_oid() ;

   public abstract void set_Subfamily1_family_oid( java.lang.String _Subfamily1_family_oid ) ;

   public abstract java.lang.String get_Subfamily1_subfamily_oid() ;

   public abstract void set_Subfamily1_subfamily_oid( java.lang.String _Subfamily1_subfamily_oid ) ;

   public abstract java.lang.String get_Family_oid() ;

   public abstract void set_Family_oid( java.lang.String _Family_oid ) ;

   public abstract java.lang.String get_Subfamily2_family_oid() ;

   public abstract void set_Subfamily2_family_oid( java.lang.String _Subfamily2_family_oid ) ;

   public abstract java.lang.String get_Subfamily2_subfamily_oid() ;

   public abstract void set_Subfamily2_subfamily_oid( java.lang.String _Subfamily2_subfamily_oid ) ;

}
