/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.escuela.modelo;

/**
 * Value object for Profesor.
 *
 */
public class ProfesorValue
   extends java.lang.Object
   implements java.io.Serializable 
{

   private static final long serialVersionUID = 1L;

   private java.lang.String nombre;
   private boolean nombreHasBeenSet = false;
   private java.lang.String codigo;
   private boolean codigoHasBeenSet = false;

   public ProfesorValue()
   {
   }

   //TODO Cloneable is better than this !
   public ProfesorValue( ProfesorValue otherValue )
   {
	  this.nombre = otherValue.nombre;
	  nombreHasBeenSet = true;
	  this.codigo = otherValue.codigo;
	  codigoHasBeenSet = true;
   }

   public java.lang.String getNombre()
   {
	  return this.nombre;
   }

   public void setNombre( java.lang.String nombre )
   {
	  this.nombre = nombre;
	  nombreHasBeenSet = true;
   }

   public boolean nombreHasBeenSet(){
	  return nombreHasBeenSet;
   }
   public java.lang.String getCodigo()
   {
	  return this.codigo;
   }

   public void setCodigo( java.lang.String codigo )
   {
	  this.codigo = codigo;
	  codigoHasBeenSet = true;
   }

   public boolean codigoHasBeenSet(){
	  return codigoHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("nombre=" + getNombre() + " " + "codigo=" + getCodigo());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && codigoHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof ProfesorValue)
	  {
		 ProfesorValue that = (ProfesorValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.codigo == null )
		 {
			lEquals = lEquals && ( that.codigo == null );
		 }
		 else
		 {
			lEquals = lEquals && this.codigo.equals( that.codigo );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof ProfesorValue)
	  {
		 ProfesorValue that = (ProfesorValue) other;
		 boolean lEquals = true;
		 if( this.nombre == null )
		 {
			lEquals = lEquals && ( that.nombre == null );
		 }
		 else
		 {
			lEquals = lEquals && this.nombre.equals( that.nombre );
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.nombre != null) ? this.nombre.hashCode() : 0);

      result = 37*result + ((this.codigo != null) ? this.codigo.hashCode() : 0);

	  return result;
   }

}
