/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Home interface for AverageSpeed.
 */
public interface AverageSpeedHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AverageSpeed";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.model/AverageSpeed";

   public org.openxava.test.model.AverageSpeedRemote create(java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.AverageSpeedRemote create(org.openxava.test.model.AverageSpeedData data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.AverageSpeedRemote create(org.openxava.test.model.AverageSpeedValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public java.util.Collection findByVehicle(java.lang.String oid)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByDriver(java.lang.Integer number)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.AverageSpeedRemote findByOid(java.lang.String oid)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.AverageSpeedRemote findByPrimaryKey(org.openxava.test.model.AverageSpeedKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
