/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

import java.util.*;

import org.openxava.util.*;

/**
 * Primary key for CustomerState.
 */
public class CustomerStateKey
   extends java.lang.Object
   implements java.io.Serializable
{

   private static final long serialVersionUID = 1L;

   public java.lang.String _State_id;
   public int _Customer_number;

   public CustomerStateKey()
   {
   }

   public CustomerStateKey( java.lang.String _State_id,int _Customer_number )
   {
      this._State_id = _State_id;
      this._Customer_number = _Customer_number;
   }

   public java.lang.String get_State_id()
   {
      return _State_id;
   }
   public int get_Customer_number()
   {
      return _Customer_number;
   }

   public void set_State_id(java.lang.String _State_id)
   {
      this._State_id = _State_id;
   }
   public void set_Customer_number(int _Customer_number)
   {
      this._Customer_number = _Customer_number;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this._State_id != null) _hashCode += this._State_id.hashCode();
         _hashCode += (int)this._Customer_number;

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.openxava.test.model.CustomerStateKey) )
         return false;

      org.openxava.test.model.CustomerStateKey pk = (org.openxava.test.model.CustomerStateKey)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this._State_id != null )
         {
            eq = eq && this._State_id.equals( pk.get_State_id() );
         }
         else  // this._State_id == null
         {
            eq = eq && ( pk.get_State_id() == null );
         }
         eq = eq && this._Customer_number == pk._Customer_number;
      }

      return eq;
   }

   /**
    * Create from a string with the format of toString() method
    */
   public static CustomerStateKey createFromString(String string) throws IllegalArgumentException, IllegalAccessException {
      StringTokenizer st = new StringTokenizer(string, "[.]");
      CustomerStateKey key = new CustomerStateKey();
      java.lang.reflect.Field [] fields = key.getClass().getFields();
      Arrays.sort(fields, FieldComparator.getInstance());
      for (int i = 0; i < fields.length; i++) {
         String v = st.nextToken();
         Class type = fields[i].getType();
         Object value = null;
         if (!type.equals(String.class)) {
            value = Strings.toObject(type, v);
         }
         else {
            value = string;
         }
         fields[i].set(key, value);
      }
      return key;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
      java.lang.reflect.Field [] fields = getClass().getFields();
      Arrays.sort(fields, FieldComparator.getInstance());
      for (int i=0; i < fields.length; i++) {
      	try {
      	 	toStringValue.append(fields[i].get(this)).append('.');
      	}
      	catch (IllegalAccessException ex) {
      	 	ex.printStackTrace();
      	 	toStringValue.append(" ").append('.');
      	}
      }
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
