/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Home interface for DeliveryPlace.
 */
public interface DeliveryPlaceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DeliveryPlace";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.model/DeliveryPlace";

   public org.openxava.test.model.DeliveryPlaceRemote create(org.openxava.test.model.CustomerRemote container , int counter , java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote create(org.openxava.test.model.CustomerKey containerKey , int counter , java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote create(org.openxava.test.model.CustomerRemote container , int counter , org.openxava.test.model.DeliveryPlaceData data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote create(org.openxava.test.model.CustomerRemote container , int counter , org.openxava.test.model.DeliveryPlaceValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote create(org.openxava.test.model.CustomerKey containerKey , int counter , org.openxava.test.model.DeliveryPlaceValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public java.util.Collection findByCustomer(int number)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByPreferredWarehouse(java.lang.Integer number, int zoneNumber)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.DeliveryPlaceRemote findByPrimaryKey(org.openxava.test.model.DeliveryPlaceKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
