/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Home interface for ShipmentCharge.
 */
public interface ShipmentChargeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ShipmentCharge";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.model/ShipmentCharge";

   public org.openxava.test.model.ShipmentChargeRemote create(java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.ShipmentChargeRemote create(org.openxava.test.model.ShipmentChargeData data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.ShipmentChargeRemote create(org.openxava.test.model.ShipmentChargeValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public java.util.Collection findByShipment(java.lang.String type, int mode, int number)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.ShipmentChargeRemote findByPrimaryKey(org.openxava.test.model.ShipmentChargeKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
