/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.model;

/**
 * Home interface for Vehicle.
 */
public interface VehicleHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Vehicle";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.model/Vehicle";

   public org.openxava.test.model.VehicleRemote create(java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.VehicleRemote create(org.openxava.test.model.VehicleData data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.VehicleRemote create(org.openxava.test.model.VehicleValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.model.VehicleRemote findByOid(java.lang.String oid)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.model.VehicleRemote findByPrimaryKey(org.openxava.test.model.VehicleKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
