/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Remote interface for Family.
 */
public interface Family
   extends org.openxava.ejbx.EJBReplicable
{

   public java.lang.String getOid(  )
      throws java.rmi.RemoteException;

   public int getNumber(  )
      throws java.rmi.RemoteException;

   public void setNumber( int newNumber )
      throws java.rmi.RemoteException;

   public java.lang.String getDescription(  )
      throws java.rmi.RemoteException;

   public void setDescription( java.lang.String newDescription )
      throws java.rmi.RemoteException;

}
