/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Value object for Product3.
 *
 */
public class Product3Value
   extends java.lang.Object
   implements java.io.Serializable 
{

   private static final long serialVersionUID = 1L;

   private java.lang.String comments;
   private boolean commentsHasBeenSet = false;
   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private long number;
   private boolean numberHasBeenSet = false;
   private java.lang.String family_oid;
   private boolean family_oidHasBeenSet = false;

   public Product3Value()
   {
   }

   //TODO Cloneable is better than this !
   public Product3Value( Product3Value otherValue )
   {
	  this.comments = otherValue.comments;
	  commentsHasBeenSet = true;
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	  this.number = otherValue.number;
	  numberHasBeenSet = true;
	  this.family_oid = otherValue.family_oid;
	  family_oidHasBeenSet = true;
   }

   public java.lang.String getComments()
   {
	  return this.comments;
   }

   public void setComments( java.lang.String comments )
   {
	  this.comments = comments;
	  commentsHasBeenSet = true;
   }

   public boolean commentsHasBeenSet(){
	  return commentsHasBeenSet;
   }
   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;
   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }
   public long getNumber()
   {
	  return this.number;
   }

   public void setNumber( long number )
   {
	  this.number = number;
	  numberHasBeenSet = true;
   }

   public boolean numberHasBeenSet(){
	  return numberHasBeenSet;
   }
   public java.lang.String getFamily_oid()
   {
	  return this.family_oid;
   }

   public void setFamily_oid( java.lang.String family_oid )
   {
	  this.family_oid = family_oid;
	  family_oidHasBeenSet = true;
   }

   public boolean family_oidHasBeenSet(){
	  return family_oidHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("comments=" + getComments() + " " + "description=" + getDescription() + " " + "number=" + getNumber() + " " + "family_oid=" + getFamily_oid());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && numberHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof Product3Value)
	  {
		 Product3Value that = (Product3Value) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 lEquals = lEquals && this.number == that.number;

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof Product3Value)
	  {
		 Product3Value that = (Product3Value) other;
		 boolean lEquals = true;
		 if( this.comments == null )
		 {
			lEquals = lEquals && ( that.comments == null );
		 }
		 else
		 {
			lEquals = lEquals && this.comments.equals( that.comments );
		 }
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.family_oid == null )
		 {
			lEquals = lEquals && ( that.family_oid == null );
		 }
		 else
		 {
			lEquals = lEquals && this.family_oid.equals( that.family_oid );
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.comments != null) ? this.comments.hashCode() : 0);

      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

      result = 37*result + (int)(number^(number>>>32));

      result = 37*result + ((this.family_oid != null) ? this.family_oid.hashCode() : 0);

	  return result;
   }

}
