/*
 * Generated by XDoclet - Do not edit!
 */
package org.xavax.school.model;

/**
 * Home interface for Teacher.
 */
public interface TeacherHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Teacher";
   public static final String JNDI_NAME="@subcontext@/ejb/org.xavax.school.model/Teacher";

   public org.xavax.school.model.Teacher create(java.util.Map values)
      throws javax.ejb.CreateException,org.xavax.validators.ValidationException,java.rmi.RemoteException;

   public org.xavax.school.model.Teacher create(org.xavax.school.model.TeacherData data)
      throws javax.ejb.CreateException,org.xavax.validators.ValidationException,java.rmi.RemoteException;

   public org.xavax.school.model.Teacher create(org.xavax.school.model.TeacherValue value)
      throws javax.ejb.CreateException,org.xavax.validators.ValidationException,java.rmi.RemoteException;

   public org.xavax.school.model.Teacher findByPrimaryKey(org.xavax.school.model.TeacherKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
