

// File generated by OpenXava: Wed Jun 27 09:57:00 CEST 2007
// Archivo generado por OpenXava: Wed Jun 27 09:57:00 CEST 2007

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Teacher		Java interface for entity/Interfaz java para Entidad

package org.openxava.school.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ITeacher  extends org.openxava.model.IModel {	

	// Properties/Propiedades 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	String getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}