/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Remote interface for AdditionalDetail.
 */
public interface AdditionalDetail
   extends org.openxava.ejbx.EJBReplicable, org.openxava.test.ejb.IAdditionalDetail
{

   public int getCounter(  )
      throws java.rmi.RemoteException;

   public int getSubfamily(  )
      throws java.rmi.RemoteException;

   public void setSubfamily( int newSubfamily )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.Service getService(  )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.ServiceKey getServiceKey(  )
      throws java.rmi.RemoteException;

   public int getService_number(  )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.ServiceType getType(  )
      throws java.rmi.RemoteException;

   public void setType( org.openxava.test.ejb.ServiceType newType )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.ServiceTypeKey getTypeKey(  )
      throws java.rmi.RemoteException;

   public void setTypeKey( org.openxava.test.ejb.ServiceTypeKey key )
      throws java.rmi.RemoteException;

   public int getType_number(  )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.AdditionalDetailData getData(  )
      throws java.rmi.RemoteException;

   public void setData( org.openxava.test.ejb.AdditionalDetailData data )
      throws java.rmi.RemoteException;

   public org.openxava.test.ejb.AdditionalDetailValue getAdditionalDetailValue(  )
      throws java.rmi.RemoteException;

   public void setAdditionalDetailValue( org.openxava.test.ejb.AdditionalDetailValue value )
      throws java.rmi.RemoteException;

}
