/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Data object for Delivery.
 */
public class DeliveryData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.String _Distance;
   private java.lang.String _Incidents;
   private java.lang.String _DriverType;
   private java.lang.String _Remarks;
   private java.lang.String _Employee;
   private java.lang.String _Description;
   private java.lang.String _Vehicle;
   private int date_day;
   private int date_month;
   private int date_year;
   private int number;
   private int type_number;
   private java.lang.Integer carrier_number;
   private int invoice_year;
   private int invoice_number;

  /*
  // begin value object
   private org.openxava.test.ejb.DeliveryValue DeliveryValue = null;

   public org.openxava.test.ejb.DeliveryValue getDeliveryValue()
   {
	  if( DeliveryValue == null )
	  {
          DeliveryValue = new org.openxava.test.ejb.DeliveryValue();
	  }
      try
         {
            DeliveryValue.setDistance( getDistance() );
            DeliveryValue.setIncidents( getIncidents() );
            DeliveryValue.setDriverType( getDriverType() );
            DeliveryValue.setRemarks( getRemarks() );
            DeliveryValue.setEmployee( getEmployee() );
            DeliveryValue.setDescription( getDescription() );
            DeliveryValue.setVehicle( getVehicle() );
            DeliveryValue.setTransportMode( getTransportMode() );
            DeliveryValue.setDate( getDate() );
            DeliveryValue.setNumber( getNumber() );
            DeliveryValue.setType_number( getType_number() );
            DeliveryValue.setCarrier_number( getCarrier_number() );
            DeliveryValue.setInvoice_year( getInvoice_year() );
            DeliveryValue.setInvoice_number( getInvoice_number() );
                   }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return DeliveryValue;
   }

   public void setDeliveryValue( org.openxava.test.ejb.DeliveryValue valueHolder )
   {

	  try
	  {
		 setDistance( valueHolder.getDistance() );
		 setIncidents( valueHolder.getIncidents() );
		 setDriverType( valueHolder.getDriverType() );
		 setRemarks( valueHolder.getRemarks() );
		 setEmployee( valueHolder.getEmployee() );
		 setDescription( valueHolder.getDescription() );
		 setVehicle( valueHolder.getVehicle() );
		 setTransportMode( valueHolder.getTransportMode() );
		 setDate( valueHolder.getDate() );
		 setCarrier_number( valueHolder.getCarrier_number() );
	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

  // end value object

 */

   public DeliveryData()
   {
   }

  /*
   public DeliveryData( java.lang.String _Distance,java.lang.String _Incidents,java.lang.String _DriverType,java.lang.String _Remarks,java.lang.String _Employee,java.lang.String _Description,java.lang.String _Vehicle,int date_day,int date_month,int date_year,int number,int type_number,java.lang.Integer carrier_number,int invoice_year,int invoice_number )
   {
      set_Distance(_Distance);
      set_Incidents(_Incidents);
      set_DriverType(_DriverType);
      set_Remarks(_Remarks);
      set_Employee(_Employee);
      set_Description(_Description);
      set_Vehicle(_Vehicle);
      setDate_day(date_day);
      setDate_month(date_month);
      setDate_year(date_year);
      setNumber(number);
      setType_number(type_number);
      setCarrier_number(carrier_number);
      setInvoice_year(invoice_year);
      setInvoice_number(invoice_number);
   }
   */

   public DeliveryData( DeliveryData otherData )
   {
      set_Distance(otherData.get_Distance());
      set_Incidents(otherData.get_Incidents());
      set_DriverType(otherData.get_DriverType());
      set_Remarks(otherData.get_Remarks());
      set_Employee(otherData.get_Employee());
      set_Description(otherData.get_Description());
      set_Vehicle(otherData.get_Vehicle());
      setDate_day(otherData.getDate_day());
      setDate_month(otherData.getDate_month());
      setDate_year(otherData.getDate_year());
      setNumber(otherData.getNumber());
      setType_number(otherData.getType_number());
      setCarrier_number(otherData.getCarrier_number());
      setInvoice_year(otherData.getInvoice_year());
      setInvoice_number(otherData.getInvoice_number());

   }

   public org.openxava.test.ejb.DeliveryKey getPrimaryKey() {
     org.openxava.test.ejb.DeliveryKey pk = new org.openxava.test.ejb.DeliveryKey(this.getNumber(),this.getType_number(),this.getInvoice_year(),this.getInvoice_number());
     return pk;
   }

   public java.lang.String get_Distance()
   {
      return this._Distance;
   }
   public void set_Distance( java.lang.String _Distance )
   {
      this._Distance = _Distance;
   }

   public java.lang.String get_Incidents()
   {
      return this._Incidents;
   }
   public void set_Incidents( java.lang.String _Incidents )
   {
      this._Incidents = _Incidents;
   }

   public java.lang.String get_DriverType()
   {
      return this._DriverType;
   }
   public void set_DriverType( java.lang.String _DriverType )
   {
      this._DriverType = _DriverType;
   }

   public java.lang.String get_Remarks()
   {
      return this._Remarks;
   }
   public void set_Remarks( java.lang.String _Remarks )
   {
      this._Remarks = _Remarks;
   }

   public java.lang.String get_Employee()
   {
      return this._Employee;
   }
   public void set_Employee( java.lang.String _Employee )
   {
      this._Employee = _Employee;
   }

   public java.lang.String get_Description()
   {
      return this._Description;
   }
   public void set_Description( java.lang.String _Description )
   {
      this._Description = _Description;
   }

   public java.lang.String get_Vehicle()
   {
      return this._Vehicle;
   }
   public void set_Vehicle( java.lang.String _Vehicle )
   {
      this._Vehicle = _Vehicle;
   }

   public int getDate_day()
   {
      return this.date_day;
   }
   public void setDate_day( int date_day )
   {
      this.date_day = date_day;
   }

   public int getDate_month()
   {
      return this.date_month;
   }
   public void setDate_month( int date_month )
   {
      this.date_month = date_month;
   }

   public int getDate_year()
   {
      return this.date_year;
   }
   public void setDate_year( int date_year )
   {
      this.date_year = date_year;
   }

   public int getNumber()
   {
      return this.number;
   }
   public void setNumber( int number )
   {
      this.number = number;
   }

   public int getType_number()
   {
      return this.type_number;
   }
   public void setType_number( int type_number )
   {
      this.type_number = type_number;
   }

   public java.lang.Integer getCarrier_number()
   {
      return this.carrier_number;
   }
   public void setCarrier_number( java.lang.Integer carrier_number )
   {
      this.carrier_number = carrier_number;
   }

   public int getInvoice_year()
   {
      return this.invoice_year;
   }
   public void setInvoice_year( int invoice_year )
   {
      this.invoice_year = invoice_year;
   }

   public int getInvoice_number()
   {
      return this.invoice_number;
   }
   public void setInvoice_number( int invoice_number )
   {
      this.invoice_number = invoice_number;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("_Distance=" + get_Distance() + " " + "_Incidents=" + get_Incidents() + " " + "_DriverType=" + get_DriverType() + " " + "_Remarks=" + get_Remarks() + " " + "_Employee=" + get_Employee() + " " + "_Description=" + get_Description() + " " + "_Vehicle=" + get_Vehicle() + " " + "date_day=" + getDate_day() + " " + "date_month=" + getDate_month() + " " + "date_year=" + getDate_year() + " " + "number=" + getNumber() + " " + "type_number=" + getType_number() + " " + "carrier_number=" + getCarrier_number() + " " + "invoice_year=" + getInvoice_year() + " " + "invoice_number=" + getInvoice_number());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof DeliveryData )
      {
         DeliveryData lTest = (DeliveryData) pOther;
         boolean lEquals = true;

         if( this._Distance == null )
         {
            lEquals = lEquals && ( lTest._Distance == null );
         }
         else
         {
            lEquals = lEquals && this._Distance.equals( lTest._Distance );
         }
         if( this._Incidents == null )
         {
            lEquals = lEquals && ( lTest._Incidents == null );
         }
         else
         {
            lEquals = lEquals && this._Incidents.equals( lTest._Incidents );
         }
         if( this._DriverType == null )
         {
            lEquals = lEquals && ( lTest._DriverType == null );
         }
         else
         {
            lEquals = lEquals && this._DriverType.equals( lTest._DriverType );
         }
         if( this._Remarks == null )
         {
            lEquals = lEquals && ( lTest._Remarks == null );
         }
         else
         {
            lEquals = lEquals && this._Remarks.equals( lTest._Remarks );
         }
         if( this._Employee == null )
         {
            lEquals = lEquals && ( lTest._Employee == null );
         }
         else
         {
            lEquals = lEquals && this._Employee.equals( lTest._Employee );
         }
         if( this._Description == null )
         {
            lEquals = lEquals && ( lTest._Description == null );
         }
         else
         {
            lEquals = lEquals && this._Description.equals( lTest._Description );
         }
         if( this._Vehicle == null )
         {
            lEquals = lEquals && ( lTest._Vehicle == null );
         }
         else
         {
            lEquals = lEquals && this._Vehicle.equals( lTest._Vehicle );
         }
         lEquals = lEquals && this.date_day == lTest.date_day;
         lEquals = lEquals && this.date_month == lTest.date_month;
         lEquals = lEquals && this.date_year == lTest.date_year;
         lEquals = lEquals && this.number == lTest.number;
         lEquals = lEquals && this.type_number == lTest.type_number;
         if( this.carrier_number == null )
         {
            lEquals = lEquals && ( lTest.carrier_number == null );
         }
         else
         {
            lEquals = lEquals && this.carrier_number.equals( lTest.carrier_number );
         }
         lEquals = lEquals && this.invoice_year == lTest.invoice_year;
         lEquals = lEquals && this.invoice_number == lTest.invoice_number;

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this._Distance != null) ? this._Distance.hashCode() : 0);

      result = 37*result + ((this._Incidents != null) ? this._Incidents.hashCode() : 0);

      result = 37*result + ((this._DriverType != null) ? this._DriverType.hashCode() : 0);

      result = 37*result + ((this._Remarks != null) ? this._Remarks.hashCode() : 0);

      result = 37*result + ((this._Employee != null) ? this._Employee.hashCode() : 0);

      result = 37*result + ((this._Description != null) ? this._Description.hashCode() : 0);

      result = 37*result + ((this._Vehicle != null) ? this._Vehicle.hashCode() : 0);

      result = 37*result + (int) date_day;

      result = 37*result + (int) date_month;

      result = 37*result + (int) date_year;

      result = 37*result + (int) number;

      result = 37*result + (int) type_number;

      result = 37*result + ((this.carrier_number != null) ? this.carrier_number.hashCode() : 0);

      result = 37*result + (int) invoice_year;

      result = 37*result + (int) invoice_number;

      return result;
   }

}
