/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Primary key for Office2.
 */
public class Office2Key
   extends java.lang.Object
   implements java.io.Serializable
{

   public int zoneNumber;
   public int number;
   public java.lang.Integer mainWarehouse_number;

   public Office2Key()
   {
   }

   public Office2Key( int zoneNumber,int number,java.lang.Integer mainWarehouse_number )
   {
      this.zoneNumber = zoneNumber;
      this.number = number;
      this.mainWarehouse_number = mainWarehouse_number;
   }

   public int getZoneNumber()
   {
      return zoneNumber;
   }
   public int getNumber()
   {
      return number;
   }
   public java.lang.Integer getMainWarehouse_number()
   {
      return mainWarehouse_number;
   }

   public void setZoneNumber(int zoneNumber)
   {
      this.zoneNumber = zoneNumber;
   }
   public void setNumber(int number)
   {
      this.number = number;
   }
   public void setMainWarehouse_number(java.lang.Integer mainWarehouse_number)
   {
      this.mainWarehouse_number = mainWarehouse_number;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         _hashCode += (int)this.zoneNumber;
         _hashCode += (int)this.number;
         if (this.mainWarehouse_number != null) _hashCode += this.mainWarehouse_number.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.openxava.test.ejb.Office2Key) )
         return false;

      org.openxava.test.ejb.Office2Key pk = (org.openxava.test.ejb.Office2Key)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         eq = eq && this.zoneNumber == pk.zoneNumber;
         eq = eq && this.number == pk.number;
         if( this.mainWarehouse_number != null )
         {
            eq = eq && this.mainWarehouse_number.equals( pk.getMainWarehouse_number() );
         }
         else  // this.mainWarehouse_number == null
         {
            eq = eq && ( pk.getMainWarehouse_number() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
      java.lang.reflect.Field [] fields = getClass().getFields();
      for (int i=0; i < fields.length; i++) {
      	try {
      	 	toStringValue.append(fields[i].get(this)).append('.');
      	}
      	catch (IllegalAccessException ex) {
      	 	ex.printStackTrace();
      	 	toStringValue.append(" ").append('.');
      	}
      }
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
