/*
 * Generated by XDoclet - Do not edit!
 */
package org.openxava.test.ejb;

/**
 * Home interface for Product.
 */
public interface ProductHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Product";
   public static final String JNDI_NAME="@subcontext@/ejb/org.openxava.test.ejb/Product";

   public org.openxava.test.ejb.Product create(java.util.Map values)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.ejb.Product create(org.openxava.test.ejb.ProductData data)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public org.openxava.test.ejb.Product create(org.openxava.test.ejb.ProductValue value)
      throws javax.ejb.CreateException,org.openxava.validators.ValidationException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.openxava.test.ejb.Product findByPrimaryKey(org.openxava.test.ejb.ProductKey pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
